services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 13000:3000
